version: "3.7"

services:
    jaegar:
        image: jaegertracing/all-in-one:1.28
        hostname: jaegar
        environment:
            - COLLECTOR_ZIPKIN_HOST_PORT=:9411
        ports:
            - 5775:5775/udp
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 16686:16686 # UI Port
            - 14268:14268
            - 14250:14250
            - 9411:9411
    
    # zipkin:
    #     image: openzipkin/zipkin
    #     ports:
    #         - 9411:9411
